name: RDP Setup

on: workflow_dispatch

jobs:
  setup-rdp:
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
      # 1. تنزيل Ngrok و NSSM
      - name: Download Ngrok & NSSM
        run: |
          $NgrokUrl = "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/ngrok.exe"
          $NssmUrl = "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/nssm.exe"

          if (!(Test-Path -Path "./ngrok.exe")) {
            Invoke-WebRequest $NgrokUrl -OutFile ngrok.exe
            Write-Host "Ngrok downloaded successfully."
          } else {
            Write-Host "Ngrok is already downloaded."
          }

          if (!(Test-Path -Path "./nssm.exe")) {
            Invoke-WebRequest $NssmUrl -OutFile nssm.exe
            Write-Host "NSSM downloaded successfully."
          } else {
            Write-Host "NSSM is already downloaded."
          }

      # 2. نسخ Ngrok و NSSM إلى System32
      - name: Copy Ngrok & NSSM to System32
        run: |
          copy ngrok.exe C:\Windows\System32 || exit /b 1
          copy nssm.exe C:\Windows\System32 || exit /b 1

      # 3. مصادقة Ngrok
      - name: Authenticate Ngrok
        run: |
          .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      # 4. تنزيل الملفات الإضافية
      - name: Download Additional Files
        run: |
          $NgrokUsBatUrl = "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/NGROK-US.bat"
          $NgrokCheckBatUrl = "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/NGROK-CHECK.bat"
          $LoopBatUrl = "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/loop.bat"

          if (!(Test-Path -Path "./NGROK-US.bat")) {
            Invoke-WebRequest $NgrokUsBatUrl -OutFile NGROK-US.bat
            Write-Host "NGROK-US.bat downloaded successfully."
          } else {
            Write-Host "NGROK-US.bat is already downloaded."
          }

          if (!(Test-Path -Path "./NGROK-CHECK.bat")) {
            Invoke-WebRequest $NgrokCheckBatUrl -OutFile NGROK-CHECK.bat
            Write-Host "NGROK-CHECK.bat downloaded successfully."
          } else {
            Write-Host "NGROK-CHECK.bat is already downloaded."
          }

          if (!(Test-Path -Path "./loop.bat")) {
            Invoke-WebRequest $LoopBatUrl -OutFile loop.bat
            Write-Host "loop.bat downloaded successfully."
          } else {
            Write-Host "loop.bat is already downloaded."
          }

      # 5. إعداد Ngrok Tunnel
      - name: Configure Ngrok Tunnel
        run: |
          start NGROK-US.bat

      # 6. تمكين الوصول إلى RDP
      - name: Enable RDP Access
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      # 7. تشغيل Ngrok
      - name: Start Ngrok Service
        run: |
          sc start ngrok || exit /b 1

      # 8. التحقق من الإعداد
      - name: Verify Setup
        run: cmd /c NGROK-CHECK.bat

      # 9. مراقبة النفق
      - name: Monitor Ngrok Tunnel
        run: cmd /c loop.bat
