name: RDP Setup

on: workflow_dispatch

jobs:
  setup-rdp:
    runs-on: windows-latest
    timeout-minutes: 120
    env:
      NGROK_URL: "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/ngrok.exe"
      NSSM_URL: "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/nssm.exe"
      NGROK_US_BAT_URL: "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/NGROK-US.bat"
      NGROK_CHECK_BAT_URL: "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/NGROK-CHECK.bat"
      LOOP_BAT_URL: "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/loop.bat"

    steps:
      # 1. التحقق من المتغيرات
      - name: Validate Environment Variables
        run: |
          if (!$Env:NGROK_URL -or !$Env:NSSM_URL -or !$Env:NGROK_US_BAT_URL -or !$Env:NGROK_CHECK_BAT_URL -or !$Env:LOOP_BAT_URL) {
            Write-Error "One or more environment variables are not set. Exiting."
            exit /b 1
          }
          Write-Host "NGROK_URL: $Env:NGROK_URL"
          Write-Host "NSSM_URL: $Env:NSSM_URL"
          Write-Host "NGROK_US_BAT_URL: $Env:NGROK_US_BAT_URL"
          Write-Host "NGROK_CHECK_BAT_URL: $Env:NGROK_CHECK_BAT_URL"
          Write-Host "LOOP_BAT_URL: $Env:LOOP_BAT_URL"

      # 2. تنزيل Ngrok و NSSM
      - name: Download Ngrok & NSSM
        run: |
          if (!(Test-Path -Path "./ngrok.exe")) {
            Invoke-WebRequest $Env:NGROK_URL -OutFile ngrok.exe
            Write-Host "Ngrok downloaded successfully."
          } else {
            Write-Host "Ngrok is already downloaded."
          }

          if (!(Test-Path -Path "./nssm.exe")) {
            Invoke-WebRequest $Env:NSSM_URL -OutFile nssm.exe
            Write-Host "NSSM downloaded successfully."
          } else {
            Write-Host "NSSM is already downloaded."
          }

      # 3. نسخ Ngrok و NSSM إلى System32
      - name: Copy Ngrok & NSSM to System32
        run: |
          copy ngrok.exe C:\Windows\System32 || exit /b 1
          copy nssm.exe C:\Windows\System32 || exit /b 1

      # 4. مصادقة Ngrok
      - name: Authenticate Ngrok
        run: |
          .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      # 5. تنزيل الملفات الإضافية
      - name: Download Additional Files
        run: |
          if (!(Test-Path -Path "./NGROK-US.bat")) {
            Invoke-WebRequest $Env:NGROK_US_BAT_URL -OutFile NGROK-US.bat
            Write-Host "NGROK-US.bat downloaded successfully."
          } else {
            Write-Host "NGROK-US.bat is already downloaded."
          }

          if (!(Test-Path -Path "./NGROK-CHECK.bat")) {
            Invoke-WebRequest $Env:NGROK_CHECK_BAT_URL -OutFile NGROK-CHECK.bat
            Write-Host "NGROK-CHECK.bat downloaded successfully."
          } else {
            Write-Host "NGROK-CHECK.bat is already downloaded."
          }

          if (!(Test-Path -Path "./loop.bat")) {
            Invoke-WebRequest $Env:LOOP_BAT_URL -OutFile loop.bat
            Write-Host "loop.bat downloaded successfully."
          } else {
            Write-Host "loop.bat is already downloaded."
          }

      # 6. إعداد Ngrok Tunnel
      - name: Configure Ngrok Tunnel
        run: |
          start NGROK-US.bat

      # 7. تمكين الوصول إلى RDP
      - name: Enable RDP Access
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      # 8. تشغيل Ngrok
      - name: Start Ngrok Service
        run: |
          sc start ngrok || exit /b 1

      # 9. التحقق من الإعداد
      - name: Verify Setup
        run: cmd /c NGROK-CHECK.bat

      # 10. مراقبة النفق
      - name: Monitor Ngrok Tunnel
        run: cmd /c loop.bat
