name: RDP Setup

on: workflow_dispatch

jobs:

  setup-rdp:
    runs-on: windows-latest
    timeout-minutes: 1200

    steps:

    # 1. إعداد المتغيرات
    - name: Set Variables
      run: |
        $Env:NGROK_URL = "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/ngrok.exe"
        $Env:NSSM_URL = "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/nssm.exe"
        $Env:NGROK_US_BAT_URL = "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/NGROK-US.bat"
        $Env:NGROK_CHECK_BAT_URL = "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/NGROK-CHECK.bat"
        $Env:LOOP_BAT_URL = "https://raw.githubusercontent.com/doctornesa/RDP-3/refs/heads/master/FILES/loop.bat"

    # 2. تنزيل Ngrok و NSSM
    - name: Download Ngrok & NSSM
      run: |
        if (!(Test-Path -Path "./ngrok.exe")) {
          Invoke-WebRequest $Env:NGROK_URL -OutFile ngrok.exe
        } else {
          Write-Host "Ngrok is already downloaded."
        }
        if (!(Test-Path -Path "./nssm.exe")) {
          Invoke-WebRequest $Env:NSSM_URL -OutFile nssm.exe
        } else {
          Write-Host "NSSM is already downloaded."
        }

    # 3. نسخ Ngrok و NSSM إلى نظام Windows
    - name: Copy Ngrok & NSSM to System32
      run: |
        copy ngrok.exe C:\Windows\System32 || exit /b 1
        copy nssm.exe C:\Windows\System32 || exit /b 1

    # 4. المصادقة مع Ngrok باستخدام GitHub Secrets
    - name: Authenticate Ngrok
      run: |
        .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    # 5. تنزيل الملفات الإضافية
    - name: Download Additional Files
      run: |
        if (!(Test-Path -Path "./NGROK-US.bat")) {
          Invoke-WebRequest $Env:NGROK_US_BAT_URL -OutFile NGROK-US.bat
        }
        if (!(Test-Path -Path "./NGROK-CHECK.bat")) {
          Invoke-WebRequest $Env:NGROK_CHECK_BAT_URL -OutFile NGROK-CHECK.bat
        }
        if (!(Test-Path -Path "./loop.bat")) {
          Invoke-WebRequest $Env:LOOP_BAT_URL -OutFile loop.bat
        }

    # 6. إعداد Ngrok Tunnel
    - name: Configure Ngrok Tunnel
      run: |
        start NGROK-US.bat

    # 7. تمكين الوصول إلى RDP
    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    # 8. تشغيل Ngrok
    - name: Start Ngrok Service
      run: |
        sc start ngrok || exit /b 1

    # 9. التحقق من الإعداد
    - name: Verify Setup
      run: cmd /c NGROK-CHECK.bat

    # 10. مراقبة النفق
    - name: Monitor Ngrok Tunnel
      run: cmd /c loop.bat
