name: CI

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Download Ngrok & NSSM

      run: |

        Invoke-WebRequest https://raw.githubusercontent.com/T36k0/RDP/main/FILES/ngrok.exe?token=AJIPFUUFWLUOSOPQ7HHW47LA6KD52 -OutFile ngrok.exe

        Invoke-WebRequest https://raw.githubusercontent.com/T36k0/RDP/main/FILES/nssm.exe?token=AJIPFUTGNWMTVHRUGNHZD53A6KDZ2 -OutFile nssm.exe

    - name: Copy NSSM & Ngrok to Windows Directory.

      run: | 

        copy nssm.exe C:\Windows\System32

        copy ngrok.exe C:\Windows\System32

    - name: Connect your NGROK account

      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Download Important Files.

      run: |

        Invoke-WebRequest https://raw.githubusercontent.com/T36k0/RDP/main/FILES/NGROK-US.bat?token=AJIPFURHM7TTA2TMORYKKTDA6KDMO -OutFile NGROK-US.bat

        Invoke-WebRequest https://raw.githubusercontent.com/T36k0/RDP/main/FILES/NGROK-CHECK.bat?token=AJIPFUXCJPI4JL256L3B36LA6KDOM -OutFile NGROK-CHECK.bat

        Invoke-WebRequest https://raw.githubusercontent.com/T36k0/RDP/main/FILES/loop.bat?token=AJIPFUXBZXSSXLDNF2HHIHDA6KDSI -OutFile loop.bat

    - name: Make YML file for NGROK.

      run: start NGROK-US.bat

    - name: Enable RDP Access.

      run: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Create Tunnel

      run: sc start ngrok
      
    - name: All Done!

      run: cmd /c NGROK-CHECK.bat
      
    - name: Enjoy

      run: cmd /c loop.bat
